module.exports = {
  caseType:'renovation_delivery_package', initialState:'requirements_captured',
  states:['requirements_captured','site_verified','design_options','takeoff_review','budget_scheduled','permit_review','change_control','approved','delivered'],
  createRoles:['project_manager','designer'],
  evidenceKinds:['site_constraint_digest','licensed_design_asset','dimensioned_plan','quantity_takeoff','cost_catalog_snapshot','schedule_baseline','permit_record','change_order','inspection_record'],
  requiredSignals:['measurementUnit','dimensionCheckStatus','costCatalogVersion','scheduleBaselineVersion','permitStatus','policyVersion'],
  assessmentRoles:['designer','estimator','project_manager','qualified_contractor'],
  auditRoles:['project_manager','qualified_contractor','owner'],
  connectorRoles:['project_manager','qualified_contractor'],
  professionalBoundary:'Outputs are planning aids, not licensed design, code, permit, or constructability approval; qualified professionals remain in control.',
  connectors:[
    {name:'cad_bim_gis',purpose:'dimensioned plan references'},
    {name:'product_cost_catalog',purpose:'versioned quantity and cost inputs'},
    {name:'render_worker',purpose:'render and export manifests'},
    {name:'contractor',purpose:'bid and qualified review receipts'},
    {name:'object_storage',purpose:'encrypted deliverable pointers'},
    {name:'permitting',purpose:'permit and inspection status'},
  ],
  transitions:[
    {from:'requirements_captured',action:'verify_site',to:'site_verified',roles:['designer','contractor'],requiresEvidence:true},
    {from:'site_verified',action:'record_design_options',to:'design_options',roles:['designer'],requiresEvidence:true},
    {from:'design_options',action:'review_takeoff',to:'takeoff_review',roles:['estimator'],requiresEvidence:true},
    {from:'takeoff_review',action:'baseline_budget_schedule',to:'budget_scheduled',roles:['project_manager'],requiresEvidence:true,dualControl:true},
    {from:'budget_scheduled',action:'submit_permit_review',to:'permit_review',roles:['qualified_contractor'],requiresEvidence:true},
    {from:'permit_review',action:'open_change_control',to:'change_control',roles:['project_manager','owner'],requiresEvidence:true},
    {from:'change_control',action:'approve',to:'approved',roles:['owner','qualified_contractor'],requiresEvidence:true,dualControl:true},
    {from:'approved',action:'deliver',to:'delivered',roles:['project_manager'],requiresEvidence:true,dualControl:true},
  ],
  assess:x=>({disposition:x.dimensionCheckStatus==='verified'&&x.permitStatus!=='rejected'?'qualified_constructability_review_required':'design_or_permit_hold',codeCompliance:null,assumptions:{unit:x.measurementUnit,costCatalog:x.costCatalogVersion,schedule:x.scheduleBaselineVersion}}),
};
